version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: webpack-reactjs-web
    volumes: 
      - ".:/app"
    ports:
      - "3001:3000"
    tty: true