apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-16T20:57:05Z"
  generation: 1
  labels:
    app: webpack-reactjs-web
  name: webpack-reactjs-web
  namespace: default
  resourceVersion: "1896"
  uid: 867e8ce2-2c09-4949-a647-78d0264c7128
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webpack-reactjs-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webpack-reactjs-web
    spec:
      containers:
      - image: caprilespe/webpack-reactjs-web:v1
        imagePullPolicy: IfNotPresent
        name: webpack-reactjs-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-16T20:57:15Z"
    lastUpdateTime: "2022-01-16T20:57:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-16T20:57:05Z"
    lastUpdateTime: "2022-01-16T20:57:15Z"
    message: ReplicaSet "webpack-reactjs-web-84b6575f8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
